---
- hosts: centos
  tasks:
    - name: Cambio parametro SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding'
        line: X11Forwarding no

    - name: Reiniciando servicio SSH
      service:
        name: sshd
        state: restarted
...        
