---
- name: Actualizando Ubuntu Server 18.04 a 20.04 LTS
  hosts: 192.168.1.151
  gather_facts: yes
  become: yes
  tasks:
    # Use a block to perform tasks conditionally—only if running Ubuntu 12.04.
    - block:
      - debug:
          msg: 'This server is running Ubuntu 18.04 LTS and will be upgraded to 20.04 LTS.'
      # Now would be a good time to take a backup if you can trigger an
      # automated backup!
      - name: Remove the EOL message of the day if one exists.
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - /etc/update-motd.d/99-esm
          - /run/motd.dynamic

      - name: Upgrade all packages to the latest version
        apt: update_cache=yes upgrade=full

      - name: Ensure update-manager-core is installed.
        apt: name=update-manager-core state=present

      - name: Run do-release-upgrade non-interactively.
        command: do-release-upgrade -f DistUpgradeViewNonInteractive

      #- name: Reboot the server.
      #  reboot:
      - name: Check if a reboot is needed on all servers
        register: reboot_required_file
        stat:
          path: /var/run/reboot-required
          get_md5: no

      - name: Reboot the server if kernel updated
        reboot:
          msg: "Reboot initiated by Ansible for kernel updates"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
        when: reboot_required_file.stat.exists
