---
- name: Configuracion Discos ASM
  hosts: centos
  become: true
  gather_facts: false
  tasks:
    - name: Creando Particion
      parted: 
        device: "{{ item }}"
        part_start: 0%
        part_end: 100%
        number: 1
        state: present
      with_items:
        - /dev/sdb
        - /dev/sdc
    
    - name: Creando Disco ASM
      shell:
        cmd: "oracleasm createdisk DISCOPRUEBA01 /dev/sdb1"

    - name: Creando Disco ASM
      shell:
        cmd: "oracleasm createdisk DISCOPRUEBA02 /dev/sdc1"

    - name: Scaneando Discos ASM
      shell:
        cmd: "oracleasm scandisks"
    
    - name: Listando Discos ASM
      shell:
        cmd: "oracleasm listdisks"
...
